#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
@project: PyCharm
@file: app_layout.py
@author: Shengqiang Zhang
@time: 2019/8/10 01:09
@mail: sqzhang77@gmail.com
"""

import dash_table
import dash_core_components as dcc
import dash_html_components as html
from dash_table.Format import Format, Scheme, Sign, Symbol



# html元素布局
# 完全嵌入在python代码中
# 仅适合简单web页面的快速搭建，复杂页面不建议使用dash开发
# 如果你对以下布局代码不了解，请勿随意修改代码
app_layout = html.Div([

    html.Div(
        className = 'row',
        children=[

            dcc.Input(
                id='upload_file_success_flag',
                type='number',
                value=1,
                style={'display': 'none'}
            ),

            # 在浏览器中存储数据，每次刷新页面或者载入页面都会被清空
            dcc.Store(id='store_memory_history_data')
        ]
    ),


    # 上传历史记录文件
    html.Div(
        className='row',
        children=[
            html.Div(
                className='five columns',
                children=[
                    dcc.Upload(
                        id='dcc_upload_file',
                        children=html.Div([
                            html.A(
                                id='upload_link',
                                children='点击上传Chrome历史记录文件',
                                style={'cursor': 'pointer'}
                            )
                        ]),
                        style={
                            'width': '100%',
                            'height': '60px',
                            'lineHeight': '60px',
                            'borderWidth': '1px',
                            'borderStyle': 'dashed',
                            'borderRadius': '5px',
                            'textAlign': 'center',
                            'margin-top': '10px',
                            'margin-bottom': '20px'
                        },

                        # Allow multiple files to be uploaded
                        multiple=False
                    ),
                ]
            ),
